import Foundation

struct IssueReportEnvironment: Equatable {
    let appVersion: String
    let buildNumber: String
    let macOSVersion: String
    let architecture: String
    let variant: String
    let asrProvider: String
    let llmProvider: String

    static var current: IssueReportEnvironment {
        let info = Bundle.main.infoDictionary
        return IssueReportEnvironment(
            appVersion: info?["CFBundleShortVersionString"] as? String ?? "unknown",
            buildNumber: info?["CFBundleVersion"] as? String ?? "unknown",
            macOSVersion: ProcessInfo.processInfo.operatingSystemVersionString,
            architecture: runtimeArchitecture,
            variant: buildVariant,
            asrProvider: KeychainService.selectedASRProvider.rawValue,
            llmProvider: KeychainService.selectedLLMProvider.rawValue
        )
    }

    var markdown: String {
        """
        - Type4Me: \(appVersion) (\(buildNumber))
        - 版本类型 / Variant: \(variant)
        - macOS: \(macOSVersion)
        - 运行架构 / Architecture: \(architecture)
        - ASR: \(asrProvider)
        - LLM: \(llmProvider)
        """
    }

    private static var runtimeArchitecture: String {
        #if arch(arm64)
        return "arm64"
        #elseif arch(x86_64)
        return "x86_64"
        #else
        return "unknown"
        #endif
    }

    private static var buildVariant: String {
        #if HAS_CLOUD_SUBSCRIPTION
        return "official"
        #elseif HAS_SHERPA_ONNX
        return "local"
        #else
        return "pure"
        #endif
    }
}

enum IssueReportService {
    static let repositoryNewIssueURL = URL(string: "https://github.com/joewongjc/type4me/issues/new")!
    static let maximumReportLogCharacters = 40_000
    static let maximumBrowserURLCharacters = 7_500

    static func suggestedTitle(customTitle: String, description: String) -> String {
        let trimmedTitle = customTitle.trimmingCharacters(in: .whitespacesAndNewlines)
        if !trimmedTitle.isEmpty {
            return String(trimmedTitle.prefix(100))
        }

        let firstLine = description
            .split(whereSeparator: { $0.isNewline })
            .first
            .map(String.init)?
            .trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        let summary = firstLine.isEmpty ? "问题反馈" : String(firstLine.prefix(70))
        return "[Bug] \(summary)"
    }

    static func fullReport(
        description: String,
        environment: IssueReportEnvironment,
        includeLogs: Bool,
        logText: String
    ) -> String {
        var sections = [
            "## 问题描述 / Description\n\n\(description.trimmingCharacters(in: .whitespacesAndNewlines))",
            "## 环境信息 / Environment\n\n\(environment.markdown)"
        ]

        if includeLogs {
            let sanitized = cappedSuffix(
                sanitizedLog(logText),
                maximumCharacters: maximumReportLogCharacters,
                omissionMarker: "[earlier log entries omitted]\n"
            )
            let safeLog = sanitized.isEmpty
                ? "[no debug log available]"
                : sanitized.replacingOccurrences(of: "```", with: "``\\`")
            sections.append(
                """
                ## 诊断日志 / Diagnostic log

                <details open>
                <summary>已自动脱敏 / Automatically redacted</summary>

                ```text
                \(safeLog)
                ```
                </details>
                """
            )
        }

        sections.append("_Generated by Type4Me's built-in issue reporter._")
        return sections.joined(separator: "\n\n")
    }

    static func githubIssueURL(
        title: String,
        description: String,
        environment: IssueReportEnvironment,
        includeLogs: Bool,
        logText: String
    ) -> URL? {
        let sanitized = sanitizedLog(logText)
        var descriptionLimit = 1_200
        var logLimit = includeLogs ? 2_000 : 0

        for _ in 0..<16 {
            let body = browserBody(
                description: description,
                environment: environment,
                includeLogs: includeLogs,
                sanitizedLog: sanitized,
                descriptionLimit: descriptionLimit,
                logLimit: logLimit
            )
            guard let url = makeIssueURL(title: title, body: body) else { return nil }
            if url.absoluteString.count <= maximumBrowserURLCharacters {
                return url
            }
            if logLimit > 160 {
                logLimit /= 2
            } else if logLimit > 0 {
                logLimit = 0
            } else if descriptionLimit > 240 {
                descriptionLimit /= 2
            } else {
                return makeIssueURL(
                    title: title,
                    body: "## 环境信息 / Environment\n\n\(environment.markdown)\n\n完整报告已复制到剪贴板，请粘贴到这里。\nThe full report has been copied to the clipboard; please paste it here."
                )
            }
        }
        return nil
    }

    static func sanitizedLog(_ raw: String) -> String {
        let replacements: [(pattern: String, template: String)] = [
            (#"(?i)(authorization\s*[:=]\s*bearer\s+)[^\s\"']+"#, "$1<redacted>"),
            (#"(?i)(bearer\s+)[A-Z0-9._~+/=-]+"#, "$1<redacted>"),
            (#"(?i)((?:\"?(?:api[_-]?key|access[_-]?key|access[_-]?token|token|secret|password)\"?)\s*[:=]\s*\"?)[^\"'\s,&}\]]+"#, "$1<redacted>"),
            (#"(?i)([?&](?:api[_-]?key|access[_-]?key|access[_-]?token|token|secret|password)=)[^&\s]+"#, "$1<redacted>"),
            (#"(?im)(value=).*$"#, "$1<redacted>"),
            (#"(?im)(args=).*$"#, "$1<redacted>"),
            (#"(?im)(macAction: no tool_call in LLM reply:).*$"#, "$1 <redacted>"),
            (#"(?im)(macAction: (?:success|failed)\b).*$"#, "$1 <redacted>"),
            (#"(?i)[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}"#, "<redacted-email>"),
            (#"/Users/[^/\s]+"#, "~")
        ]

        return replacements.reduce(raw) { text, replacement in
            guard let regex = try? NSRegularExpression(pattern: replacement.pattern) else {
                return text
            }
            let range = NSRange(text.startIndex..., in: text)
            return regex.stringByReplacingMatches(
                in: text,
                range: range,
                withTemplate: replacement.template
            )
        }
    }

    private static func browserBody(
        description: String,
        environment: IssueReportEnvironment,
        includeLogs: Bool,
        sanitizedLog: String,
        descriptionLimit: Int,
        logLimit: Int
    ) -> String {
        let compactDescription = cappedPrefix(
            description.trimmingCharacters(in: .whitespacesAndNewlines),
            maximumCharacters: descriptionLimit,
            omissionMarker: "\n\n[description truncated; full report is on the clipboard]"
        )
        var body = "## 问题描述 / Description\n\n\(compactDescription)\n\n## 环境信息 / Environment\n\n\(environment.markdown)"

        if includeLogs && logLimit > 0 {
            let excerpt = cappedSuffix(
                sanitizedLog,
                maximumCharacters: logLimit,
                omissionMarker: "[earlier log entries omitted]\n"
            ).replacingOccurrences(of: "```", with: "``\\`")
            body += "\n\n## 日志摘要 / Log excerpt\n\n```text\n\(excerpt)\n```"
        }

        body += "\n\n> 完整脱敏报告已复制到剪贴板；如果预填内容不完整，请粘贴替换。\n> The full redacted report is on the clipboard; paste it here if needed."
        return body
    }

    private static func makeIssueURL(title: String, body: String) -> URL? {
        var components = URLComponents(url: repositoryNewIssueURL, resolvingAgainstBaseURL: false)
        components?.queryItems = [
            URLQueryItem(name: "title", value: title),
            URLQueryItem(name: "body", value: body)
        ]
        return components?.url
    }

    private static func cappedPrefix(
        _ text: String,
        maximumCharacters: Int,
        omissionMarker: String
    ) -> String {
        guard text.count > maximumCharacters else { return text }
        return String(text.prefix(maximumCharacters)) + omissionMarker
    }

    private static func cappedSuffix(
        _ text: String,
        maximumCharacters: Int,
        omissionMarker: String
    ) -> String {
        guard text.count > maximumCharacters else { return text }
        return omissionMarker + String(text.suffix(maximumCharacters))
    }
}
